<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [33]:
import numpy as np

array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [34]:
array_2d = array_1d.reshape(2,5)
array_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [35]:
array = [0, 2, 0, 3, 0, 4, 0]
indices_valores_0 = np.nonzero(array)[0]
indices_valores_0

array([1, 3, 5])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [36]:
array3x3 = np.random.randint(0,2,(3,3))
array3x3

array([[0, 1, 0],
       [0, 1, 1],
       [0, 0, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [37]:
array_10numeros = np.random.randint(0,10,10)

print(f"Array 10 numeros --> {array_10numeros}")
print(f"Valor máximo --> {np.max(array_10numeros)}")
print(f"Valor mínimo --> {np.min(array_10numeros)}")


Array 10 numeros --> [5 5 9 2 5 3 7 1 9 0]
Valor máximo --> 9
Valor mínimo --> 0


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [38]:
array_ejemplo = np.random.randint(0,10,10)
print(f"Array original --> {array_ejemplo}")

array_ejemplo_invertido = array_ejemplo[::-1]
print(f"Array invertido --> {array_ejemplo_invertido}")

Array original --> [4 5 7 1 7 9 9 8 9 9]
Array invertido --> [9 9 8 9 9 7 1 7 5 4]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [39]:
#Generar array tridimensional de dimensiones (2,3,4) con valores del 1 al 24
array_6 = np.random.randint(1,25,(2,3,4))
print(f"Array --> {array_6}")

#Seleccionar el primer 15 del array  (no se si vale con la forma que lo he hecho o se buscaba hacerlo con el .where())
primer_15 = array_6[array_6 == 15][0]
print(f"Primer 15 --> {primer_15}\n")

#Seleccionar todos los elementos del primer array
elementos_primer_array6 = array_6[0,::]
print(f"Todos los elementos del primer array --> {elementos_primer_array6}\n")

#Seleccionar ultima fila del ultimo array
ultima_fila_array6 = array_6[-1,::]
print(f"Ultima fila del array --> {ultima_fila_array6}\n")


Array --> [[[16  8 17 14]
  [21  7  4 20]
  [11 21 14 15]]

 [[10 11  7  2]
  [12 18  7 19]
  [23  1 23  4]]]
Primer 15 --> 15

Todos los elementos del primer array --> [[16  8 17 14]
 [21  7  4 20]
 [11 21 14 15]]

Ultima fila del array --> [[10 11  7  2]
 [12 18  7 19]
 [23  1 23  4]]




#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [40]:
#Generamos array de 3x3x5
array_7 = np.random.randint(1,31,(3,2,5))
print(f"Array --> {array_7}\n")

#Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.
dos_primeros_elementos_cada_fila = array_7[0,:,:2]
print(f"2 primeros elementos de cada fila del primer array --> {dos_primeros_elementos_cada_fila}")

#Selecciona el subarray que contiene todas las filas de los dos últimos arrays.
subarray = array_7[-2,:,:]#este no me queda muy claro lo que se pide
print(f"Subarrays que contienen las filas de los 2 ultimos arrays --> {subarray}")

Array --> [[[24 16 16  5  8]
  [18  4 28  5 17]]

 [[28 13  2 22 11]
  [28 15 10 23 19]]

 [[15 25  3 13 26]
  [15 29 12 15 11]]]

2 primeros elementos de cada fila del primer array --> [[24 16]
 [18  4]]
Subarrays que contienen las filas de los 2 ultimos arrays --> [[28 13  2 22 11]
 [28 15 10 23 19]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [41]:
#Generamos array de 4x3x2
array_8 = np.random.randint(1,25,(4,3,2))
print(array_8)

#Cambia todos los elementos de la segunda fila del segundo array por `0`.
print('\nAhora modificamos todos los elementos de la segunda fila del segundo array por `0`')
array_8[1,::] = 0
print(array_8)

#Cambia todos los valores del último array a `-1`.
print('\nAhora modificamos todos los valores del último array a `-1`')
array_8[-1,::] = -1
print(array_8)

[[[ 6 11]
  [ 3  4]
  [16 20]]

 [[21 11]
  [17 21]
  [14  4]]

 [[16 23]
  [20 16]
  [13 17]]

 [[17 20]
  [23 14]
  [ 3 14]]]

Ahora modificamos todos los elementos de la segunda fila del segundo array por `0`
[[[ 6 11]
  [ 3  4]
  [16 20]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[16 23]
  [20 16]
  [13 17]]

 [[17 20]
  [23 14]
  [ 3 14]]]

Ahora modificamos todos los valores del último array a `-1`
[[[ 6 11]
  [ 3  4]
  [16 20]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[16 23]
  [20 16]
  [13 17]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [42]:
#Generamos array de 2x4x3
array_9 = np.arange(-10,14)
print(f"Array --> {array_9}")

#Selecccionamos los mayores a 5
mayores_a_5 = array_9[array_9 > 5]
print(f"Elementos mayores a 5 --> {mayores_a_5}")

#Remplazamos todos los elementos negativos por 0
array_sin_negativos = array_9.copy()
array_sin_negativos[array_sin_negativos < 0] = 0
print(f"Array sin negativos --> {array_sin_negativos}")

Array --> [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10  11  12  13]
Elementos mayores a 5 --> [ 6  7  8  9 10 11 12 13]
Array sin negativos --> [ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10 11 12 13]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [43]:
#Generamos Array
array_10 = np.random.randint(1,28,(3,3,3))
print(f"Array --> {array_10}\n")

# Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.
subarray = array_10[1,:,:2]
print(f"subarray --> {subarray}\n")

# Selecciona todos los elementos del tercer array que sean mayores que `20`.
elementos = array_10[2][array_10[2] > 20]
print(f"Elemetos del tercer array mayores a 20 --> {elementos}")

Array --> [[[27  4 20]
  [19  1 11]
  [24 21 18]]

 [[ 7  6 15]
  [11 16 26]
  [ 4 12 20]]

 [[26 24 27]
  [ 3 21  1]
  [ 6  9 27]]]

subarray --> [[ 7  6]
 [11 16]
 [ 4 12]]

Elemetos del tercer array mayores a 20 --> [26 24 27 21 27]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [44]:
array_aleatorio = np.random.randint(1,1000, 10)
array_aleatorio[array_aleatorio == np.min(array_aleatorio)] = 0
array_aleatorio[array_aleatorio == np.max(array_aleatorio)] = 0
array_aleatorio

array([792, 917, 732, 642, 740, 718, 885,   0, 441,   0], dtype=int32)

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [45]:
array_12 = np.random.randint(1,101,15)
print(f"Array deshordenado --> {array_12}")

array12_ordenado = np.sort(array_12)
print(f"Array ordenado --> {array12_ordenado}")

Array deshordenado --> [ 1 62 19 65 55 87 53 71 11 67 55 43 46 11 15]
Array ordenado --> [ 1 11 11 15 19 43 46 53 55 55 62 65 67 71 87]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [46]:
matriz = np.random.randint(1,11,(4,4))
print(matriz)

suma_filas = np.sum(matriz, axis=1)
suma_columnas = np.sum(matriz, axis=0)

print(f"\nSuma de filas --> {suma_filas}\n")
print(f"Suma de filas --> {suma_filas}")

[[8 8 1 2]
 [1 8 7 3]
 [3 9 4 1]
 [3 2 7 2]]

Suma de filas --> [19 19 17 14]

Suma de filas --> [19 19 17 14]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [47]:
matriz2 = np.zeros((5,5))
matriz2[0,:] = -1
matriz2[:,0] = -1
matriz2[:,-1] = -1
matriz2[-1,:] = -1

print(matriz2)

[[-1. -1. -1. -1. -1.]
 [-1.  0.  0.  0. -1.]
 [-1.  0.  0.  0. -1.]
 [-1.  0.  0.  0. -1.]
 [-1. -1. -1. -1. -1.]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [48]:
array13 = np.random.randint(0,101, 10)
print("Array --> ",array13)

print("Media --> ", np.mean(array13))
print("Desviación Estandar --> ", np.std(array13))

Array -->  [72 30 10 72 52 80 62 79 63  5]
Media -->  52.5
Desviación Estandar -->  26.435771220072244


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [49]:
#generamos array 2x3x4
array14 = np.random.randint(1,25,(2,3,4))
print(f"Array --> {array14}")

#                                                           0  1  2     2  1  0
# Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).
array_transpuesto = np.transpose(array14, (2, 1, 0))
print(array_transpuesto)

Array --> [[[ 4 18 18  3]
  [13 24 12  2]
  [22  3 10 19]]

 [[11  2 19  9]
  [21 21 13  4]
  [20  4 20 13]]]
[[[ 4 11]
  [13 21]
  [22 20]]

 [[18  2]
  [24 21]
  [ 3  4]]

 [[18 19]
  [12 13]
  [10 20]]

 [[ 3  9]
  [ 2  4]
  [19 13]]]


Lo que ha pasado es que lo que antes eran 2 arrays con 3 filas y 4 columnas, 
ahora son 4 arrays con 3 filas y 2 columnas.

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [50]:
array15 = np.random.randint(1,25,(3,4,2))
print("Array --> ", array15)

array15_transpuesto = np.swapaxes(array15, 0, 1)
print("\nArray transpuesto en x e y --> ", array15_transpuesto)

Array -->  [[[17  7]
  [ 4 12]
  [24 17]
  [ 4  5]]

 [[15 13]
  [11  3]
  [15 22]
  [ 6  7]]

 [[ 9  6]
  [ 6 22]
  [ 3  9]
  [14 21]]]

Array transpuesto en x e y -->  [[[17  7]
  [15 13]
  [ 9  6]]

 [[ 4 12]
  [11  3]
  [ 6 22]]

 [[24 17]
  [15 22]
  [ 3  9]]

 [[ 4  5]
  [ 6  7]
  [14 21]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [51]:
array16 = np.random.randint(1,25,(3,2,4))
print("Array --> ",array16)

array16_transpuesto = np.transpose(array16, (2,0,1))
print("Array tridimensional en formato 4,3,2 --> ",array16_transpuesto)

Array -->  [[[ 2 11 20  8]
  [ 7 17  4  2]]

 [[11  5 11 11]
  [20 14  5  2]]

 [[18 11  3 16]
  [ 4 22 20  7]]]
Array tridimensional en formato 4,3,2 -->  [[[ 2  7]
  [11 20]
  [18  4]]

 [[11 17]
  [ 5 14]
  [11 22]]

 [[20  4]
  [11  5]
  [ 3 20]]

 [[ 8  2]
  [11  2]
  [16  7]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [52]:
array17 = np.random.randint(-10,10, size=(3,4,5))
print("Array --> ", array17)

array_vacio = np.empty_like(array17)
print("\nArray vacio --> ", array_vacio)

mediana = np.median(array17)
maximo = np.max(array17)
minimo = np.min(array17)

array_vacio = np.empty(array17.shape, dtype=str)

array_vacio[(array17 == maximo)] = "MAX"
array_vacio[(array17 == minimo)] = "MIN"
array_vacio[(array17 == mediana)] = "M"
array_vacio[(array17 > mediana)] = "X"
array_vacio[(array17 < mediana)] = "Y"

print("Array vacio", array_vacio)

Array -->  [[[ -6  -8   6  -1   5]
  [-10   4   0   0   7]
  [ -5  -7   7  -7 -10]
  [  8   5  -3  -4  -7]]

 [[  4   1  -7   6  -1]
  [  2  -5  -2  -7  -3]
  [  1   9  -2 -10  -4]
  [ -4   8   5   0   1]]

 [[  1   2  -6  -3  -1]
  [ -2   3  -2   3  -3]
  [  0   9   1   1  -4]
  [  6   4   9   9   8]]]

Array vacio -->  [[[ -7   8   2  -7   1]
  [ -6   8  -4  -7  -2]
  [  4  -4   9  -4   8]
  [  0  -4  -2  -2   0]]

 [[  9   8  -9  -6  -6]
  [  2   2   1   9 -10]
  [ -5   8   5  -1   5]
  [ -1  -7  -3  -3   5]]

 [[  2   9   6   5   0]
  [  1   5   2 -10   5]
  [  0   9  -7   9 -10]
  [  1  -6  -4  -8  -8]]]
Array vacio [[['Y' 'Y' 'X' 'Y' 'X']
  ['Y' 'X' 'M' 'M' 'X']
  ['Y' 'Y' 'X' 'Y' 'Y']
  ['X' 'X' 'Y' 'Y' 'Y']]

 [['X' 'X' 'Y' 'X' 'Y']
  ['X' 'Y' 'Y' 'Y' 'Y']
  ['X' 'X' 'Y' 'Y' 'Y']
  ['Y' 'X' 'X' 'M' 'X']]

 [['X' 'X' 'Y' 'Y' 'Y']
  ['Y' 'X' 'Y' 'X' 'Y']
  ['M' 'X' 'X' 'X' 'Y']
  ['X' 'X' 'X' 'X' 'X']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [53]:
matriz = np.array([[1, 2, 3, 4],
                   [2, 6, 7, 8],
                   [3, 10, 11, 12],
                   [4, 6, 11, 16]])

print("Matriz")
print(matriz)


coincidencia_encontrada = False

for i in range(4):
    for j in range(4):
        son_iguales = True
        for k in range(4):
            if matriz[i, k] != matriz[k, j]:
                son_iguales = False
                break
        
        if son_iguales:
            coincidencia_encontrada = True
            print(f"Fila {i} es igual a la columna {j}.")
            break
    if coincidencia_encontrada:
        break

if not coincidencia_encontrada:
    print("No se encontró ninguna fila que coincida con una columna.")


Matriz
[[ 1  2  3  4]
 [ 2  6  7  8]
 [ 3 10 11 12]
 [ 4  6 11 16]]
Fila 0 es igual a la columna 0.
